### ISSUE TITLE
CUDA error 13 at /home/zilun/PowerInfer/ggml-cuda.cu:9619: invalid device symbol

### ISSUE THREAD

**Issue by zilunzhang** [SJTU-IPADS/PowerInfer#108]
# Prerequisites

Before submitting your issue, please ensure the following:

- [Y] I am running the latest version of PowerInfer. Development is rapid, and as of now, there are no tagged versions.
- [Y] I have carefully read and followed the instructions in the [README.md](https://github.com/SJTU-IPADS/PowerInfer/blob/main/README.md).
- [Y] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).

# Expected Behavior

Run the LLaMA-2 7B version in a dual 3090 machine (use "export CUDA_VISIBLE_DEVICES=0" to force the powerinfer run on single card.)

# Current Behavior

llama_model_loader: - tensor   60:                   blk.30.gpu_idx i32      [ 11008,     1,     1,     1 ]
llama_model_loader: - tensor   61:                blk.30.gpu_bucket i32      [ 11008,     1,     1,     1 ]
llama_model_loader: - tensor   62:                   blk.31.gpu_idx i32      [ 11008,     1,     1,     1 ]
llama_model_loader: - tensor   63:                blk.31.gpu_bucket i32      [ 11008,     1,     1,     1 ]
llama_model_loader: unknown type i32
llama_model_loader: - kv   0:                       general.architecture str     
llama_model_loader: - kv   1:              generic.gpu_index.block_count u32     
llama_model_loader: - kv   2:                        split.vram_capacity u64     
llama_model_loader: - type  i32:   64 tensors
loaded gpu_idx, vram_required: 18011832320
apply_tensors_to_base_model: applying gpu_idx adapter from '/mnt/data/nfs/zl/Powerinfer/ReluLLaMA-7B-PowerInfer-GGUF/llama-7b-relu.powerinfer.gguf.generated.gpuidx' - please wait ...
................................................................ done (2.97 ms)
offload_ffn_split: applying augmentation to model - please wait ...

CUDA error 13 at /home/zilun/PowerInfer/ggml-cuda.cu:9619: invalid device symbol
current device: 0

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              40
On-line CPU(s) list: 0-39
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
Stepping:            7
CPU MHz:             1000.559
CPU max MHz:         2401.0000
CPU min MHz:         1000.0000
BogoMIPS:            4800.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            14080K
NUMA node0 CPU(s):   0-9,20-29
NUMA node1 CPU(s):   10-19,30-39
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
```

* Operating System, e.g. for Linux:

`$ uname -a`

```
Linux worker26-19 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* SDK version, e.g. for Linux:

```
$ python3 --version
Python 3.10.13

$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

CUDA: 12.1, CUDNN: 8.9.7, Nvidia driver: 525.105.17
```

# Failure Information (for bugs)

Please help provide information about the failure / bug.
```
CUDA error 13 at /home/zilun/PowerInfer/ggml-cuda.cu:9619: invalid device symbol
current device: 0
```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

```
./build/bin/main -m /mnt/data/nfs/zl/Powerinfer/ReluLLaMA-7B-PowerInfer-GGUF/llama-7b-relu.powerinfer.gguf -n 128 -t 8 -p "Once upon a time"
```

# Issue might be relevant: https://stackoverflow.com/questions/22364926/cuda-invalid-device-symbol-error

**Comment by Tan-YiFan** [comment]
I encountered similar problem and solved it by adding `-DCMAKE_CUDA_ARCHITECTURES=native` in `cmake` options.

In detail, I re-ran the [build](https://github.com/SJTU-IPADS/PowerInfer#build) part:

```bash
cmake -S . -B build -DLLAMA_CUBLAS=ON -DCMAKE_CUDA_ARCHITECTURES=native
cmake --build build --config Release
```

**Comment by HagonChan** [comment]
This problem is because the compilation does not use the correct CUDA architecture flag, you need to go to the official website to check the correct Compute Capability of the graphics card, for example, my NVIDIA GeForce RTX 3070 corresponds to 8.6, so the architecture flag is 86, so i just need to re-run the following bash:

```bash
cmake -S . -B build -DLLAMA_CUBLAS=ON -DCMAKE_CUDA_ARCHITECTURES=86
cmake --build build --config Release
```
